springdoc:
  oAuthFlow:
    authorizationUrlAzure: https://login.microsoftonline.com/${lan.demo.oauth2.azure.tenant}/oauth2/v2.0/authorize
  swagger-ui:
    oauth:
      client-id: ${lan.demo.oauth2.azure.clientId}
      scopes: ${lan.demo.oauth2.azure.swagger.scopes}
  paths-to-match: /api/**

spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ${lan.demo.oauth2.azure.clientId}
        profile:
          tenant-id: ${lan.demo.oauth2.azure.tenant}
        app-id-uri: ${lan.demo.oauth2.azure.app-id-uri}
