springdoc:
  oAuthFlow:
    authorizationUrlAzure: ${demo.oauth.azure.idp-url}/oauth2/v2.0/authorize
  swagger-ui:
    oauth:
      client-id: ${demo.oauth.azure.clientId}
      scopes: ${demo.oauth.azure.swagger.scopes}
  paths-to-match: /api/**

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${demo.oauth.azure.idp-url}/v2.0
          jwk-set-uri: ${demo.oauth.azure.idp-url}/discovery/v2.0/keys

demo:
  oauth:
    azure:
      idp-url: https://login.microsoftonline.com/${demo.oauth.azure.tenant}